name: "Aggregate data from all the plugins"
on: [ workflow_dispatch, workflow_call]
jobs:
  releasePluginUpdate: 
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Regenerate Repo.js
      run: |
        $pluginInfoPath = "Regeneration\plugins.json"
        $repos = Get-Content -Path $pluginInfoPath -Raw | ConvertFrom-Json
        $updatedRepos = New-Object PSCustomObject[] $repos.Count
        for (($i = 0); $i -lt $repos.Count; $i++)
        {
            Invoke-WebRequest -Uri $repos[$i].repoURL -RetryIntervalSec 20 -MaximumRetryCount 10 -OutFile localRepoFile
            $localRepo = Get-Content -Path localRepoFile -Raw | ConvertFrom-Json
            $updatedRepos[$i] = $localRepo
            Write-Output $updatedRepos
            Write-Output "---------------------------------------------------------------------------"
        }
        
        Set-Content -Path repo.json -Value (ConvertTo-Json -InputObject $updatedRepos)
    - name: Commit and push
      run: |
          git config --local user.name "[bot]github-actions_manual-release"
          git config --local user.email "[bot]github-actions_manual-release@users.noreply.github.com"
          git add "repo.json"
          git commit -m "[CI] Rebuilding repo.json from each individual plugin's Repo.json"
          git push origin main
